#!/bin/sh
F="$1"
D="$(dirname "$F")"
$BEATSTUDIO init --budget=20 --bpm=140 --file="$F"
$BEATSTUDIO step snare 4 on --file="$F"
$BEATSTUDIO step hihat 2 on --file="$F"
$BEATSTUDIO step clap 8 on --file="$F"
$BEATSTUDIO beat-render --file="$F"
$BEATSTUDIO track-import "$D/beat.wav" --name=extra --file="$F"
$BEATSTUDIO mix beat --gain=0 --file="$F"
$BEATSTUDIO mix extra --gain=-6 --pan=0.5 --file="$F"
$BEATSTUDIO preview --file="$F"
$BEATSTUDIO master --price=1 --file="$F"
$BEATSTUDIO report --file="$F"
