#!/bin/sh
F="$1"
D="$(dirname "$F")"
$BEATSTUDIO init --budget=20 --bpm=120 --file="$F"
$BEATSTUDIO generate pop --bars=1 --seed=6 --file="$F"
$BEATSTUDIO beat-render --file="$F"
$BEATSTUDIO track-import "$D/beat.wav" --name=vox --file="$F"
$BEATSTUDIO harmonize vox --interval=third --file="$F"
$BEATSTUDIO harmonize vox --interval=fifth --as=vox_fifth --gain=-8 --file="$F"
$BEATSTUDIO report --file="$F"
