#!/bin/sh
F="$1"
D="$(dirname "$F")"
$BEATSTUDIO init --budget=20 --bpm=140 --file="$F"
$BEATSTUDIO generate trap --bars=2 --seed=11 --file="$F"
$BEATSTUDIO beat-render --file="$F"
$BEATSTUDIO melody-render --file="$F"
$BEATSTUDIO strip beat --duck-from=melody --file="$F"
$BEATSTUDIO strip melody --eq-low=-6 --eq-high=3 --comp-thresh=-20 --comp-ratio=4 --delay-ms=200 --delay-feedback=0.35 --delay-mix=0.3 --file="$F"
$BEATSTUDIO mix beat --gain=0 --file="$F"
$BEATSTUDIO mix melody --gain=-6 --file="$F"
$BEATSTUDIO preview --file="$F"
$BEATSTUDIO master --price=1 --preset=warm --file="$F"
$BEATSTUDIO strip melody --clear --file="$F"
$BEATSTUDIO report --file="$F"
